# Lines configured by zsh-newuser-install
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
#zstyle :compinstall filename '/home/laith/.zshrc'


eval "$(oh-my-posh init zsh --config https://raw.githubusercontent.com/lnyousif/dotfiles/refs/heads/main/assets/oh-my-posh/theme.omp.json)"


autoload -Uz compinit
compinit
# End of lines added by compinstall