# Linux .bashrc template contents
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH
export EDITOR=micro
eval "$(starship init bash)"


# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
    for rc in ~/.bashrc.d/*; do
        if [ -f "$rc" ]; then
            . "$rc"
        fi
    done
fi
unset rc
  # Load cross-compatible Bash functions declarations from separate file.
  if [ -f "$HOME"/.myscripts/bash_functions ]; then
      \. "$HOME"/.myscripts/bash_functions
  fi

  # Load cross-compatible Bash extra functions declarations from separate file.
  if [ -f "$HOME"/.myscripts/bash_extra ]; then
      \. "$HOME"/.myscripts/bash_extra
  fi


  # Load cross-compatible Bash alias definitions from separate file.
  if [ -f "$HOME"/.myscripts/bash_aliases ]; then
      \. "$HOME"/.myscripts/bash_aliases
  fi
