# Linux .bashrc template contents
# .bashrc
export PATH=$PATH:/usr/bin/:/usr/local/bin

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
# Add custom commands directory to PATH
if [ -d "$HOME/.myscripts/bin" ] && ! [[ "$PATH" =~ "$HOME/.myscripts/bin" ]]; then
    PATH="$HOME/.myscripts/bin:$PATH"
fi
export PATH
export EDITOR=micro
eval "$(starship init bash)"


# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
    for rc in ~/.bashrc.d/*; do
        if [ -f "$rc" ]; then
            . "$rc"
        fi
    done
fi
unset rc
  # Load cross-compatible Bash functions declarations from separate file.
  if [ -f "$HOME"/.myscripts/bash_functions ]; then
      \. "$HOME"/.myscripts/bash_functions
  fi

  # Load cross-compatible Bash extra functions declarations from separate file.
  if [ -f "$HOME"/.myscripts/bash_extra ]; then
      \. "$HOME"/.myscripts/bash_extra
  fi


  # Load cross-compatible Bash alias definitions from separate file.
  if [ -f "$HOME"/.myscripts/bash_aliases ]; then
      \. "$HOME"/.myscripts/bash_aliases
  fi


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PNPM_HOME="/home/laith/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
