packages:
  base:
    linux:
      common:
        apt:
          - git
          - curl
          - python3-pip
        apt_url:
        apt_junk:
          - firefox
          - libreoffice-data
          - gnome-boxes
          - gnome-maps
          - gnome-terminal
          - gnome-tour
          - gnome-text-editor
          - moby-engine
        dra:
          package:
          appimage:
          bin:
        kde:
        linux_cmd:
          - if ! type -P oh-my-posh >/dev/null 2>&1; then curl -s https://ohmyposh.dev/install.sh | bash -s; else oh-my-posh upgrade && oh-my-posh font install Meslo; fi
        tablet:
        pips:
          - commitizen
