packages:
  base:
    linux:
      common:
        apt:
          - git
          - curl
          - wget
          - python3-pip
          - micro
          - tmux
          - xclip
        apt_junk:
          - firefox
          - libreoffice-data
          - gnome-boxes
          - gnome-maps
          - gnome-terminal
          - gnome-tour
          - gnome-text-editor
          - moby-engine
        pips:
          - commitizen
          - pre-commit
        linux_cmd:
          - curl -sS https://starship.rs/install.sh -y | sh
