packages:
  base:
    darwin:
      brews:
        - age
        - bat
        - btop
        - curl
        - git
        - dockutil
        - pipx
        - starship
        - tmux
        - micro
      casks:
        - google-chrome
      pips:
        - commitizen
        - pre-commit
      junk:
        - Launchpad
        - Safari
        - Messages
        - Mail
        - Maps
        - Photos
        - FaceTime
        - Calendar
        - Contacts
        - Reminders
        - Notes
        - Freeform
        - TV
        - Music
        - Keynote
        - Numbers
        - Pages
        - App Store
      darwin_cmd:
        - "defaults write com.apple.finder AppleShowAllFiles true"
        - "defaults write com.apple.finder NewWindowTarget -string 'PfLo'"
